### ISSUE TITLE
I use Anaconda with python 3.6 and I have problem testing tor command

### ISSUE THREAD

**Issue by MindaugasVaitkus2** [pawelad/simple-site-crawler#1]
See error below:

(py36) C:\Users\User\Desktop\Documents\GitHub\simple-site-crawler\.tox>tox
GLOB sdist-make: C:\Users\User\Desktop\Documents\GitHub\simple-site-crawler\setup.py
py35 create: C:\Users\User\Desktop\Documents\GitHub\simple-site-crawler\.tox\py35
ERROR: InterpreterNotFound: python3.5
py36 create: C:\Users\User\Desktop\Documents\GitHub\simple-site-crawler\.tox\py36
ERROR: InterpreterNotFound: python3.6
flake8 create: C:\Users\User\Desktop\Documents\GitHub\simple-site-crawler\.tox\flake8
ERROR: invocation failed (exit code 1), logfile: C:\Users\User\Desktop\Documents\GitHub\simple-site-crawler\.tox\flake8\log\flake8-0.log
ERROR: actionid: flake8
msg: getenv
cmdargs: ['c:\\users\\user\\anaconda3\\envs\\py36\\python.exe', '-m', 'virtualenv', '--python', 'c:\\users\\user\\anaconda3\\envs\\py36\\python.exe', 'flake8']

Traceback (most recent call last):
  File "c:\users\user\anaconda3\envs\py36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\user\anaconda3\envs\py36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\users\user\anaconda3\envs\py36\lib\site-packages\virtualenv.py", line 2343, in <module>
    main()
  File "c:\users\user\anaconda3\envs\py36\lib\site-packages\virtualenv.py", line 712, in main
    symlink=options.symlink)
  File "c:\users\user\anaconda3\envs\py36\lib\site-packages\virtualenv.py", line 927, in create_environment
    site_packages=site_packages, clear=clear, symlink=symlink))
  File "c:\users\user\anaconda3\envs\py36\lib\site-packages\virtualenv.py", line 1134, in install_python
    copy_required_modules(home_dir, symlink)
  File "c:\users\user\anaconda3\envs\py36\lib\site-packages\virtualenv.py", line 1064, in copy_required_modules
    dst_filename = change_prefix(filename, dst_prefix)
  File "c:\users\user\anaconda3\envs\py36\lib\site-packages\virtualenv.py", line 1038, in change_prefix
    (filename, prefixes)
AssertionError: Filename C:\Python27\copy.py does not start with any of these prefixes: ['C:\\users\\user\\anaconda3\\envs\\py36', 'C:\\users\\user\\anaconda3\\envs\\py36']
Already using interpreter c:\users\user\anaconda3\envs\py36\python.exe
Using base prefix 'c:\\users\\user\\anaconda3\\envs\\py36'

ERROR: Error creating virtualenv. Note that some special characters (e.g. ':' and unicode symbols) in paths are not supported by virtualenv. Error details: InvocationError('c:\\users\\user\\anaconda3\\envs\\py36\\python.exe -m virtualenv --python c:\\users\\user\\anaconda3\\envs\\py36\\python.exe flake8 (see C:\\Users\\User\\Desktop\\Documents\\GitHub\\simple-site-crawler\\.tox\\flake8\\log\\flake8-0.log)', 1)
___________________________________ summary ___________________________________
ERROR:  py35: InterpreterNotFound: python3.5
ERROR:  py36: InterpreterNotFound: python3.6
ERROR:   flake8: Error creating virtualenv. Note that some special characters (e.g. ':' and unicode symbols) in paths are not supported by virtualenv. Error details: InvocationError('c:\\users\\user\\anaconda3\\envs\\py36\\python.exe -m virtualenv --python c:\\users\\user\\anaconda3\\envs\\py36\\python.exe flake8 (see C:\\Users\\User\\Desktop\\Documents\\GitHub\\simple-site-crawler\\.tox\\flake8\\log\\flake8-0.log)', 1)

(py36) C:\Users\User\Desktop\Documents\GitHub\simple-site-crawler\.tox>simple-site-crawler [2] https://seorinkodara.weebly.com
'simple-site-crawler' is not recognized as an internal or external command,
operable program or batch file.

(py36) C:\Users\User\Desktop\Documents\GitHub\simple-site-crawler\.tox>

**Comment by pawelad** [comment]
> ERROR: Error creating virtualenv. Note that some special characters (e.g. ':' and unicode symbols) in paths are not supported by virtualenv. 

I'm sorry but this seems like a problem with your local setup, not sure how I can help.

What were the commands you ere trying to run?
